server:
  port: 8899
spring:
  application:
    name: spring-boot-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #发送确认
    publisher-confirms: true
    #开启ACK
    listener:
      simple:
        acknowledge-mode: manual
    #开启发送失败退回
    publisher-returns: true
